name: Build Check

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          VITE_YORKIE_API_ADDR: ${{ secrets.VITE_YORKIE_API_ADDR }}
          VITE_YORKIE_API_KEY: ${{ secrets.VITE_YORKIE_API_KEY }}
          VITE_SERVER_BASE_URL: ${{ secrets.VITE_SERVER_BASE_URL }}
        run: npm run build
