name: Deploy to Vercel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Environment Variables File for Production
        run: |
          echo "VITE_YORKIE_API_KEY=$VITE_YORKIE_API_KEY" >> .env.production
          echo "VITE_SERVER_BASE_URL=$VITE_SERVER_BASE_URL" >> .env.production

      - name: Build project
        env:
          VITE_YORKIE_API_KEY: ${{ secrets.VITE_YORKIE_API_KEY }}
          VITE_SERVER_BASE_URL: ${{ secrets.VITE_SERVER_BASE_URL }}
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel --prod --token $VERCEL_TOKEN
